version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file: .env
  backend:
    image: k53n/kittygram_backend/
    volumes:
      - static:/backend_static
      - media:/media
    depends_on: 
      - db
    env_file: .env
  frontend:
    image: k53n/kittygram_frontend/
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
    env_file: .env
  gateway:
    image: k53n/kittygram_gateway/
    ports:
      - 9000:80
    volumes:
      - static:/static
      - media:/media
    env_file: .env
